name: Build CFA-HPC image
on:
  workflow_dispatch:
  push:
    paths:
      - containers/cfa-hpc/Dockerfile
      - .github/workflows/cfa-hpc.yml # Self-trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: holmeister73/cfa-hpc
  VERSION: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: containers/cfa-hpc
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
